export let Players = [
    {
        url_img:"https://th.bing.com/th/id/OIF.wiVCVe8uWmb2jsODTVH7ig?pid=ImgDet&rs=1",
        nom :"Cristiano Ronaldo",
        equipe :"Al Nasr",
        nationalité: "Portugais",
        num_maillot: "7",
        age:"38",

    },
    {
        url_img:"https://th.bing.com/th/id/R.4a9fbcaf4485e4bc9c1f117c7b7a971b?rik=7iJyFR%2b0V015pg&riu=http%3a%2f%2fwww.parisfans.fr%2fwp-content%2fuploads%2f2019%2f01%2fKylianMbappe-PSG.jpg&ehk=tU6Fl6KU0FGvlki%2fyKo8t1pDtYe%2fxM6VzLLiFcnyjZU%3d&risl=&pid=ImgRaw&r=0",
        nom :"Kylian Mbappé",
        equipe :"PSG",
        nationalité: "Francaise",
        num_maillot:"10",
        age:"24",
    },
    {
        url_img:"https://th.bing.com/th/id/OIP.2y8B4ScQ42M_Z0Nd5Ca9EwHaEK?pid=ImgDet&rs=1",
        nom :"Neymar",
        equipe :"AL Hilal",
        nationalité: "Brazelienne",
        num_maillot:"10",
        age:"31",
    },
    {
        url_img:"https://th.bing.com/th/id/R.8df1e953c615073cec372cc0534933d8?rik=A1hQWLZy7PCVgg&pid=ImgRaw&r=0",
        nom :"Lionel Messi",
        equipe :"Inter Miami",
        nationalité: "Argentine",
        num_maillot:"10",
        age:"36",
    },
    {
        url_img:"https://th.bing.com/th/id/R.c62de51e46e17f9f76de5b736801b4c5?rik=540nOZfXEd70Hg&pid=ImgRaw&r=0",
        nom :"Paul Pogba",
        equipe :"Manchester United",
        nationalité: "Francaise",
        num_maillot:"10",
        age:"30",
    },
    {
        url_img:"https://th.bing.com/th/id/OIP.-kRnkwT6FtASmpaLP5rSeAHaEZ?pid=ImgDet&rs=1",
        nom :"Luka Modric",
        equipe :"Real Madrid",
        nationalité: "Croatie",
        num_maillot:"10",
        age:"38",
    },
    {
        url_img:"https://th.bing.com/th/id/OIP.Ay-k6u3YqP0M6jsLZIOOoAHaEK?pid=ImgDet&rs=1",
        nom :"Caemiro",
        equipe :"Manchester United",
        nationalité: "Brezil",
        num_maillot:"18",
        age:"31",
    },
    {
        url_img:"https://th.bing.com/th/id/OIP.MciMpPNY-MnK8KfXVmJtsAHaE8?pid=ImgDet&rs=1",
        nom :"Paulo Dybala",
        equipe :"AS Rome",
        nationalité: "Argentine",
        num_maillot:"21",
        age:"29",
    },
    {
        url_img:"https://th.bing.com/th/id/R.821842355a7a3b275ff89e3424ecc163?rik=5ZL3uhoqC686zw&pid=ImgRaw&r=0",
        nom :"Trent Alexander-Arnold",
        equipe :"Liverpool",
        nationalité: "Angleterre",
        num_maillot:"66",
        age:"25",
    },
    {
        url_img:"https://th.bing.com/th/id/OIP.FwuHMQRZvfN4OPXXTmY1YQHaE8?pid=ImgDet&rs=1",
        nom :"Mohamed Salah",
        equipe :"Liverpool",
        nationalité: "Egypte",
        num_maillot:"11",
        age:"31",
    }
]